#performing logical operator
num1=int(input("Enter first number : "))
num2=int(input("Enter second number : "))
num3=int(input("Enter third number : "))
print(f"{num1<num2}={num1<num2}")
print(f"{num1}>{num2}={num1>num2}")
print(f"{num1}=={num2}={num1==num2}")
print(f"{num1}!={num2}={num1!=num2}")
print(f"{num1}<={num2}={num1<=num2}")
print(f"{num1}>={num2}={num1>=num2}")